# User Service Configuration
# Spring Boot application properties for CitaSmart User Service

# Application Configuration
spring:
  application:
    name: user-service
  profiles:
    active: dev

server:
  port: 8081

# Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/citasmart_db
    username: citasmart_user
    password: citasmart_pass
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  cache:
    type: redis
    redis:
      time-to-live: 3600000

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# Application Specific Configuration
app:
  jwt:
    secret: CitaSmartSecretKeyForJWTTokenGenerationMustBeLongEnoughForHS256
    expiration: 86400000
    refresh-expiration: 604800000
  email:
    verification:
      enabled: true
      token:
        expiration: 86400000
  password:
    reset:
      token:
        expiration: 3600000
  cors:
    allowed-origins: http://localhost:4200,http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  security:
    content-security-policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.citasmart.userservice: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
logging:
  level:
    com.citasmart.userservice: DEBUG

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/citasmart_db}
    username: ${DATABASE_USERNAME:citasmart_user}
    password: ${DATABASE_PASSWORD:citasmart_pass}
logging:
  level:
    com.citasmart.userservice: INFO
